### PR TITLE
Improve open source contribution!

### PR DESCRIPTION
**Pull request by antimatter15**
This makes the README more awesome. Please approve so I get t-Shirt.

Kthxbai

### CODE REVIEW

**Comment by anishathalye** [comment]
Hahaha thanks Kevin.

(Do you know why so many of these spam contributions have "Awesome" in them? Did someone write a bot for this or something?)

**Comment by antimatter15** [comment]
I think there was an Indian coding YouTuber who told 600k subscribers that they can get a free T-shirt by sending pull requests where you add "awesome" to READMEs

**Comment by SeerLite** [comment]
Yup that has to be it. @anishathalye hey btw you should add a "spam" or "invalid" label to the PR so it isn't counted (yes, closed PRs are also counted).

Not that that would much of a difference though, they probably already got a PR accepted somewhere.

**Comment by anishathalye** [comment]
It doesn't matter for this PR (Kevin is an irl friend of mine who sent this PR as a joke after we talked about this phenomenon). I've been tagging other ones I've seen [[1](https://github.com/hacker-tools/hacker-tools.github.io/pull/20), [2](https://github.com/bijection/sistine/pull/18), [3](https://github.com/hacker-tools/hacker-tools.github.io/pull/19), [4](https://github.com/anishathalye/mathematics-of-deep-learning/pull/1)] as spam though.

**Pull request closed without merging**
