### PR TITLE
Add PowerShell install script

### PR DESCRIPTION
**Pull request by sitiom**
Following through https://github.com/anishathalye/dotfiles_template/pull/19

### CODE REVIEW

**Comment by flickerfly** [comment]
Trying this git-submodule/install.ps1, I get the following error. It seems the Join-Path command doesn't accept three unnamed arguments on my Win 10.

Join-Path : A positional parameter cannot be found that accepts argument 'bin\dotbot'.
At C:\Users\----------\.dotfiles\install.ps1:20 char:20
+         &$PYTHON $(Join-Path $BASEDIR $DOTBOT_DIR $DOTBOT_BIN) -d $BA ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Join-Path], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.JoinPathCommand

It seems to run better if I set 
$DOTBOT_BIN = $( $DOTBOT_DIR + "\bin\dotbot")
and then 
 &$PYTHON $(Join-Path $BASEDIR $DOTBOT_BIN) -d $BASEDIR -c $CONFIG $Args

**Comment by sitiom** [comment]
> Trying this git-submodule/install.ps1, I get the following error. It seems the Join-Path command doesn't accept three unnamed arguments on my Win 10.
> 
> ```
> Join-Path : A positional parameter cannot be found that accepts argument 'bin\dotbot'.
> At C:\Users\----------\.dotfiles\install.ps1:20 char:20
> +         &$PYTHON $(Join-Path $BASEDIR $DOTBOT_DIR $DOTBOT_BIN) -d $BA ...
> +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Join-Path], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
> ```

@flickerfly Oh, my bad. Joining multiple paths seems to be only available on PowerShell Core.

**Comment by flickerfly** [comment]
Interesting quirk. Better now. :-)

**Comment by flickerfly** [comment]
Looks good

**Comment by anishathalye** [comment]
Rebased/squashed, and merged in 5f849ad. Thank you for the PR!

**Pull request closed without merging**
