### PR TITLE
Skip nonexisting target

### PR DESCRIPTION
**Pull request by ael-code**
You can follow the discussion on issue #103

### CODE REVIEW

**Comment by anishathalye** [comment]
Thanks for the fix! Merged with minor changes in 4468fff67a9e9d9f611d5dade4a9486e75dafa1c.

**Comment by ael-code** [comment]
On 11/19/2016 05:28 PM, Anish Athalye wrote:
> Thanks for the fix! Merged with minor changes in 4468fff
> <https://github.com/anishathalye/dotbot/commit/4468fff67a9e9d9f611d5dade4a9486e75dafa1c>.

I didn't get why you removed the `Skipping` word from prefix. I think it
was a good way to inform the users that one of the entry has been skipped

-- 
tommy.ael
gpg key: 0xEBD8B3682C4C4645

**Comment by anishathalye** [comment]
Oh, just to match previous behavior: https://github.com/anishathalye/dotbot/blob/master/plugins/link.py#L163

**Comment by ael-code** [comment]
On 11/19/2016 05:56 PM, Anish Athalye wrote:
> Oh, just to match previous behavior:
> https://github.com/anishathalye/dotbot/blob/master/plugins/link.py#L163
> 

It's fine then :)

**Pull request closed without merging**
