### PR TITLE
don't set executable arg to subprocess.call on Windows

### PR DESCRIPTION
**Pull request by SuJiKiNen**
as https://bugs.python.org/issue2304 said,

executable given

`C:\\Program Files\\Git\\usr\\bin\\bash.exe`

this PR is a workaround for windows.

Possiable relate to #170 

if you have to expand command like '~', you
should straight tell to use git bash like
`"bash -c 'your command'"` ,make sure that bash
is in your  `PATH`.

### CODE REVIEW

**Comment by anishathalye** [comment]
The discussion in the link makes it seem like the issue has been fixed?

**Comment by SuJiKiNen** [comment]
yeah,I dig a little deeper into the source.
[https://github.com/python/cpython/blob/4a66524006852fc982aebafa277f2c043d9ad149/Lib/subprocess.py#L977](url)
if we pass executable,
the right way to call is ` bash -c "cmd.exe /c ls"`
but actually we call  is `bash  "cmd.exe /c ls"`
and it will throw  `bash: cmd.exe /c ls: No such file or directory`
we don't have `-c` option.
that's why I suggest do not pass executable arg,
and users should be responsible to their shell commands,like `bash -c [command]`
another fix could be we just do some check for executable,and add  `-c ` option
for the executable when under Windows with git bash.
what do you think?

**Comment by mohkale** [comment]
Just to throw my two sense here. I wouldn't classify the discussion on #170 as a fix. More of a workaround. It seemed to me like dotbots shell directive wasn't working with git bash on windows, so they used cmd.exe instead. I had the same issue, with shell directives just outputting `/c: /c: Is a directory` (while using git bash on windows).

In my case the issue was two fold, first 'git bash on windows' doesn't seem to export the SHELL environment variable, which meant dotbot was defaulting to cmd.exe as the shell. I fixed it by modifying `./install` to `export SHELL`.

The second issue is that bash fails to start (with the aforementioned error message). I fixed it by removing the `shell=True` line from `dotbot/plugins/shell.py` and modifying the command to be `[executable, '-c', cmd]`. This isn't a cross platform fix, if you want to install on windows you have to install a bash like shell (or at least one that takes the `-c` flag), so I understand if you won't want to make this change in the actual repo.

**Comment by mohkale** [comment]
adding on to the previous point, I feel like issues like this would be a lot less prominent if dotbot had an API for executing shell commands. Something as simple as a `run_process.py` file which had a a method called `run_process`. As it stands different plugins appear to be using the same general format of `shell.py` meaning, at least in regards to this issue, we have to keep monkey patching the methods to make them work.

**Comment by anishathalye** [comment]
Thank you for reporting this issue and providing a pull request. I used your proposed strategy as the core of #220.

**Pull request closed without merging**
