### PR TITLE
Improve Error-Messages in link.py

### PR DESCRIPTION
**Pull request by Darksider3**
... by giving os-provided error messages to the output for linking. As discussed in #73 and #35 .

### CODE REVIEW

**Comment by Darksider3** [comment]
What is about clean.py? Should we add there to function _in_directory and _clean some exceptions(esp. on removing symlinks?).
It's possible that the User has changed something and the permissions was changed during his last install of files(or got error messages even by installing before)..

**Comment by anishathalye** [comment]
Hmm, maybe we should only show these things when the user passes `-v` using a lower log level (info or debug or something).

**Comment by Darksider3** [comment]
U surely mean Log(Log.WARNING, "Error %s:" % err.strlen) ?

**Comment by anishathalye** [comment]
`self.log.debug()` or `self.log.lowinfo()`, so that it only shows that information if people want to see it.

**Comment by Darksider3** [comment]
And now, what about the clean.py?

**Comment by Darksider3** [comment]
How about that? :-)

**Comment by anishathalye** [comment]
I know it's a small diff, but I've been kinda busy... will review this as soon as I can.

**Comment by MaikuMori** [comment]
Looks fine to me. I'm not so sure about hiding it behind debug flag. Error already is unexpected state, generally when I have error I also want the information to fix it.

Otherwise it's like just printing "ERROR", I'm looking at you Microsoft.

**Comment by Darksider3** [comment]
First commit had it on error-level, debug ID in my opinion like..m "the Specific Programm wont work. Where is the failure in this Programm? Print me more about it".
An error given by a user would be IMO not about Debugging a Programm, more about debug the configuration file written by the user.

If you hide these messages, i think there would be Chance that some User might dont understand or know to use the debug Flag for this.
Another side, are those Users your adressed Group?

**Comment by bbenne10** [comment]
I'm currently integrating dotbot into my dotfiles repo at home, and I would cast a vote that these error messages should be exposed by default. Even if they're printed directly after the "not handled" message versus on their own lines (which would be pretty trivial if we could stick with one version of python, but more difficult if we are targeting 2.7 and 3.x)

Looking over the changes, there are places where we're failing that I don't think we need to. For instance, line 75 is unconditionally setting success to False when a call to `os.makedirs` fails. I think we should probably check `err.errno` against `errno.EEXISTS` to see if the parent directory already exists and set success to `True` in this case. I'll play with this idea (once I get my zsh config linked properly -_-) and open a PR if I find the behavior to be more consistent. We can continue discussion there.

**Comment by Darksider3** [comment]
If Line 75 fails because the User got not enough permissions, the OSerror is triggered. Otherwise it shouldn't throw the error, i thought?
Testung it today in a chroot.

**Pull request closed without merging**
