### PR TITLE
Quickstart

### PR DESCRIPTION
**Pull request by Aviator45003**
This is a bash script that operates with the features outlined in #22.

### CODE REVIEW

**Comment by Aviator45003** [comment]
Known issue: Git commit step fails if gitconfig is dotbotted, because the links are not yet made.

**Comment by anishathalye** [comment]
Nice!! I've wanted to have a feature like this for a while now.

I haven't had a chance to try running the code yet, but I browsed through it, and it looks pretty good to me. I might have time to play around with running the script later this week.

I'm not sure if I have time to maintain this right now. Perhaps it's best if it's kept in a separate repository? What do you think?

You could either create a repository of your own, or I could create a `dotbot-init` repository on my account and give you commit access, whatever you prefer.



Once the tool is well-tested and everything, it could be cool to have a blog post or something showing off the script.

**Comment by Aviator45003** [comment]
I'd be happy to maintain the repository in my own git account. I already wrote another version with some cool features, such as command line arguments to test the script and customize the output, including lower the verbosity of the configuration file.

I'll push it into a repo later today.

**Comment by Aviator45003** [comment]
Do you care if I name it something like `dotbot-easy` or `easy-dotfiles`?
I assume we'd sub-repo it later?

**Comment by anishathalye** [comment]
Okay, sounds good to me. And name it whatever you like, it's your project :)

I don't think it should be a subrepo of Dotbot -- it's going to be used for initialization, it's not really a runtime dependency of Dotbot. At some point, it could be good to add a section to the readme linking to your tool.

As bad as the `curl | sh` pattern can be, some people might find it super convenient to do something like `curl -fsSL https://raw.githubusercontent.com/Aviator45003/easy-dotfiles/master/easy-dotfiles | bash` and just have everything magically set up.

**Comment by anishathalye** [comment]
I'm going to close this pull request, let's keep future discussion on this topic in #22.

**Pull request closed without merging**
