### PR TITLE
Add Dirrer for creating directories

### PR DESCRIPTION
**Pull request by casey**
I added a dir creating directive. I like it since I have a lot of files I need to link into `bin` and `.vim`.

### CODE REVIEW

**Comment by anishathalye** [comment]
Is this necessary when link supports a [create](https://github.com/anishathalye/dotfiles/blob/e19e3c756d76276534e175ec5da19ebb01c9df95/.install.conf.yaml#L13) option?

```yaml
- link:
    ~/.sbt/0.13/build.sbt:
      create: true
      path: sbt/0.13/build.sbt
```

Also, I've just been [shelling out to mkdir](https://github.com/anishathalye/dotfiles/blob/e19e3c756d76276534e175ec5da19ebb01c9df95/.install.conf.yaml#L26) to create other directories that I've needed.

```yaml
- shell:
  - mkdir -p ~/.rtorrent/session ~/.rtorrent/watch ~/.rtorrent/downloads
```

**Comment by casey** [comment]
It's just a convenience function, but I think it's worth it. In particular, it's nice to just be able to use the short form for links, and having to use the long form for a lot of links is much more verbose.

**Comment by anishathalye** [comment]
There will be a way to have defaults in Dotbot 2.0, so you can just set `create: true` as a default for linking.

**Comment by casey** [comment]
I think this could go either way, so I defer to your judgement.

A really interesting thing to do would be to look at people config files and see what common patterns are, and then try to support them better.

This search brings up tons of interesting results: https://github.com/search?utf8=%E2%9C%93&q=filename%3Ainstall.conf.yaml&type=Code&ref=searchresults

Do you know a way to do that search but return a list of filenames, so you could write a script to curl everyones config files, for further analysis?

**Comment by anishathalye** [comment]
Okay, let's pass on it for now.

Haha, I've been doing something similar to that for some time (using this search: https://github.com/search?q=DOTBOT_DIR&ref=searchresults&type=Code&utf8=%E2%9C%93). I have cloned ~600 repos on my computer (using a script to grab the search results and clone them).

It would be really interesting to look through the install.conf.yaml files for common patterns to see what could be improved / made easier.

**Comment by casey** [comment]
Could you put the script up somewhere? It could probably be adapted to extract conf files. (Or download them directly via curl, to avoid cloning the whole repo.)

**Comment by anishathalye** [comment]
https://gist.github.com/5278586119d32a0612da

(this prints the names, but it should be easy to modify it to download conf files)

**Comment by casey** [comment]
Dotbot user study in progress: github.com/casey/dotbot-user-study

**Comment by casey** [comment]
I got distracted before I could do much with the config files, but if you're interested, they're here: https://github.com/casey/dotbot-user-study/tree/master/configs

**Comment by anishathalye** [comment]
Cool! I might look into doing a more detailed user study eventually.

Also, please let me know if you end up doing more analysis!

**Comment by casey** [comment]
Was just [updating my dotfiles to pull in the latest version of dotbot](https://github.com/casey/dotfiles/commit/407d6f6cbad82abd117bab18a297fa40e9871ccf) and was reflecting on the fact that I've been using dotbot for almost 7 whole years. It's been working flawlessly the whole time, and I've used it to bootstrap my dotfiles on countless laptops, pcs, and servers.

So here's to 7 more years (at least) and thanks for such a useful tool!

**Comment by casey** [comment]
Also, I just commented here because it was the first interaction I had with the project, but I notice that dir creation was implemented, so [I can now use the `create` plugin](https://github.com/casey/dotfiles/commit/99f75b43fd65a51d82d3d4c67236671bec6b101b). Pretty sweet!

**Comment by anishathalye** [comment]
Thank you for the kind words :smile:

**Pull request closed without merging**
