### PR TITLE
Add --only and --except command-line arguments

### LINKED ISSUE #44: CLI flag to only run certain sections?
Would it make sense to add a flag to only run the clean, link, or shell sections of the config? Sometimes I dont want the shell commands to run so I just comment them out. This could be implemented using flags (dotbot -c/--clean -l/--link -s/--shell), or possibly as "sub-commands" (dotbot {clean,link,shell} or dotbot run {clean,link,shell}) and the default would still be to perform all three tasks.

I also thought it might be useful to add another optional argument to shell configurations to prompt the user if they want the shell command to run or not, something like "confirm: true". Not really sure that would be useful if I could just tell dotbot to only clean and link.

### PR DESCRIPTION
**Pull request by anishathalye**
Internal to Dotbot, we use the name "skip" instead of "except", because
the latter is a keyword, and using a name like "except_" didn't seem as
nice.

Fixes #44

### CODE REVIEW

**Comment by anishathalye** [comment]
Replying to https://github.com/anishathalye/dotbot/issues/44#issuecomment-604491525 here (cc @mohkale).

Yep, set the metavar.

Oh interesting, I hadn't thought about Dispatcher becoming part of the public API. I suppose we could stick this in the context. Is the plugin open-source, so I could take a look at it?

**Comment by mohkale** [comment]
Not open source (more just a haphazard put together mess of a plugin I use to make hierarchical and composable configs). If you want to see it, it's [here](https://github.com/mohkale/.dotfiles/blob/master/setup/plugins/subbot.py).  It depends on a few other scripts in the same directory, so if you want to try it out you'll also need [run_process](https://github.com/mohkale/.dotfiles/blob/master/setup/plugins/run_process.py) and [log_mixin](https://github.com/mohkale/.dotfiles/blob/master/setup/plugins/log_mixin.py).

**Comment by mohkale** [comment]
ping.

**Comment by anishathalye** [comment]
This seems like an interesting example of Hyrum's law -- I did not expect plugins to be instantiating their own dispatchers. I hadn't really thought of Dispatcher as part of the public API. Similarly, it feels a little strange to expose `only` / `except` in the context available to plugins.

For now, I will merge this PR as-is (I'm happy with `--only` / `--except` becoming part of the command-line interface). If at a later date we decide to expose those to plugins, that can be done without changing the command-line interface.

**Comment by mohkale** [comment]
Well, Hyrums law is new to me. Cool 😎.

**Pull request merged**
