### PR TITLE
meta: support python 3.11

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Review by kurtmckee — APPROVED** [review]
Looks good to me!

**Comment by joamatab** [comment]
can we merge and make a release for this?

**Comment by chenrui333** [comment]
anyone can take a look at this? thanks!

**Comment by anishathalye** [comment]
Thank you for the PR, and thanks all for your patience. Python 3.11 declared compatibility + testing added in https://github.com/anishathalye/dotbot/commit/eace76f6977e14e500574fa5cd9889518199782f.

**Pull request closed without merging**
