### PR TITLE
Add support for Windows and Cygwin

### LINKED ISSUE #102: Feature request: windows native symbolic link
Hello everyone,
I am using dotbot in cygwin. The link created by dotbot doesn't work for some programs, it is of this format:

    !<symlink ? home/.bashrc

The native command to create symlink is mklink in windows. How do I use it to create the symlinks?
Thank you!

### LINKED ISSUE #307: Windows symlinks are always recreated
On Windows, `os.readlink()` returns a UNC path that never matches the anticipated symlink destination. This causes dotbot to always recreate the links (example dotbot output below):

```
Incorrect link ~/.gitconfig -> \\?\C:\Users\Me\Documents\dev\dotfiles\gitconfig
```

I tested two possible fixes:

1. Use `os.path.realpath()` instead of `os.readlink()`
2. Conditionally remove the `\\?\` prefix when dotbot is running on Windows.

Option 1 results in a unit test failure:

```
[42/55] (link-relink-relative-leaves-file.bash)
relink relative does not incorrectly relink file
- test failed.
-> fail!
```

Therefore I recommend going with option 2, which gives expected results (example dotbot output below):

```
Link exists ~/.gitconfig -> C:\Users\Me\Documents\dev\dotfiles\gitconfig
```

### LINKED ISSUE #309: Support testing on Windows
This issue tracks development for testing on Windows.

This type of ticket typically generates a lot of traffic, so please only contribute to the technical discussion.

## Targets

* [x] Testing on Windows locally
* [x] Testing on Windows in CI

## Bonus targets

* [x] Testing on Cygwin locally
* [x] Testing on MacOS in CI

## Implementation

The test environment will migrate from bash scripts to Python unit tests.

### 1. Targets

@anishathalye Are the above targets acceptable to you? Are there others that need to be added?

### 2. Old Python versions

_There currently appears to be no problem testing against Python 2.7 and higher on Linux and Cygwin, but only CPython 3.8 and higher can be supported on Windows due to CPython and PyPy symlink limitations._

~To facilitate testing in Python, it might be impossible to test Python versions that are unsupported by the PSF and most Python libraries. For example, Python 2.7 through 3.4 might not be feasible test targets. This does not necessarily mean that dotbot has to drop support for those older Python versions, but it might not be possible to test them.~

~@anishathalye, do I have your okay to proceed even if this is one of the outcomes?~

### LINKED ISSUE #323: Dotbot from PyPI just won't work under Windows10
Hello,

Excuse me if I'm doing something wrong, it's the first time I'm trying to use Dotbot and I just can't get it to work under Windows. I installed it via pipx:

```bash
pipx install dotbot
```

I created a test file with `Out-File test.txt` and a `install.conf.yaml` with the following content:

```yaml
- link:
  ~/AppData/test.txt: test.txt
```

When I try to run Dotbot with `dotbot -c install.conf.yaml` I always get the following error:

```bash
Linking failed ~/AppData/test.txt -> C:\repos\dotfiles\test.txt
Some links were not successfully set up

==> Some tasks were not executed successfully
```

Any idea what I'm doing wrong? It won't work neither in PowerShell nor in Git Bash.

### PR DESCRIPTION
**Pull request by kurtmckee**
This PR introduces the following changes:

* Add full support for Windows Powershell (CPython 3.8+) and Cygwin (CPython 2.7+, PyPy 2.7, and PyPy 3.9).
* Migrate all existing unit tests from bash to Python.
* Isolate all unit test filesystem interactions so they run entirely in a temporary directory.
  This includes verification that files are not being opened or created outside the temporary directory.
* Test dotbot in CI on Linux, MacOS, and Windows, across all supported CPython and PyPy versions.
* Add code coverage reports when running locally.
  This includes summary output at the CLI and generated HTML reports in `htmlcov/`.
* Document how to run the unit tests locally, including environment setup.

The changes have been tested on these platforms:

* Windows Powershell (locally, and in CI)
* Linux (locally, and in CI)
* Cygwin (locally)
* MacOS (in CI)

Closes #102
Closes #307
Closes #309
Closes #323

### CODE REVIEW

**Comment by eengstrom** [comment]
I am excited to see the new testing framework in action - it was always challenging to develop tests for new features.  Thanks for the efforts @kurtmckee

**Comment by rgwood** [comment]
This looks like a huge improvement for dotbot on Windows, and I believe it will fix an issue I'm seeing that is closely related to #307. Thank you very much for all the work!

**Comment by kurtmckee** [comment]
Thanks all for the feedback!

@anishathalye Please let me know if you see anything that needs adjusting. I'm happy to make changes. Thanks for your work on dotbot, and for reviewing this PR!

**Comment by kurtmckee** [comment]
@anishathalye I've ported the recent repo changes over to keep this PR up-to-date. The latest commit resolves the associated merge conflicts.

**Comment by anishathalye** [comment]
This is beautiful, very thoroughly done. Thank you so much! And thank you for your patience, it took me forever to get around to looking at this.

**Comment by kurtmckee** [comment]
You're welcome, and thanks for all of your work on dotbot! 😀

**Pull request merged**
