### PR TITLE
add init-dotfiles link

### PR DESCRIPTION
**Pull request by joshblum**
Add a link to the [easy-dotfiles](https://github.com/Aviator45003/easy-dotfiles) repository.

### CODE REVIEW

**Comment by anishathalye** [comment]
I wonder if it would be better to add a separate "user-contributed" section to the README and put this in there (along with anything anyone else makes in the future).

Also, I'm going to wait till the name of the thing is finalized.

**Comment by joshblum** [comment]
Yeah waiting for the name change is good, just wanted to put this in before I forgot. 

For this specific case I feel it makes more sense to put here since new users will otherwise clone the template repo and not use the automated script..

**Comment by anishathalye** [comment]
I don't want to remove the link to the template. There may be people who are more comfortable with using something like that rather than a script.

**Comment by anishathalye** [comment]
How's this: https://github.com/anishathalye/dotbot-dev/commit/dcc3a1947a85aaa038d143f9f6a0c2a1c1a76a15

**Comment by joshblum** [comment]
Lgtm :)

**Comment by anishathalye** [comment]
Okay, done!

**Pull request closed without merging**
