### PR TITLE
Table of contents?

### PR DESCRIPTION
**Pull request by jesseleite**
What do you think of adding a table of contents, something like this, to your readme?

### CODE REVIEW

**Comment by anishathalye** [comment]
Thanks for the PR. I was recently thinking that the README has started to get large and unwieldy! This sort of thing seems like it'll be helpful.

I support this kind of reorganization. The next several days are pretty busy for me, so I'll try to take a closer look at the PR around Thursday next week.

**Comment by jesseleite** [comment]
The wiki, contribution, and license links within the table of contents, could even link directly to their respective .md files, rather than to anchors.

**Comment by anishathalye** [comment]
I tweaked things a tiny bit:

- Wiki is a direct link, as you suggested
- Removed things not directly relevant to users of Dotbot (contributing, license, packaging)
- Moved build status icon down a bit

Changes squashed in 98175a0e0a74afbdcdde3f348748a457988f8bae and merged in 86bc86add6a8ffaf5870db7b289eab576c65112b. Thank you for the contribution!

**Comment by jesseleite** [comment]
Awesome, all great changes.  Thanks again!

**Pull request closed without merging**
