### PR TITLE
Implement simple copy plugin

### PR DESCRIPTION
**Pull request by walkingice**
to address #128 , this PR implements a simple copy plugin. It only recognizes 3 options

* create
* force
* skippable

this plugin was rewriting from link plugin, so some functions are very similar with functions of link plugin.

### CODE REVIEW

**Comment by walkingice** [comment]
I think `link` and `copy` are in different context, so I created a new plugin, instead of adding option `copy:true` to `link`.

In most of cases, `link` is good enough. But I found in my use cases, sometimes I still need `copy`, so I reuse `link` plugin to create this simple `copy` plugin.

**Comment by walkingice** [comment]
Thanks for your response!

I agree DSL complexity should be reduced. just my opinion: `link` plugin reminds user the linux command `ln`, adding option `copy: true` is not easy to understand, because there is not any concept about copying inside `ln`. 

in terms of examples, I think `copy` is like providing default config to a new system. In my use case, I have 2 laptops, one for work, one for personal. Both laptops need similar `~/.gitconfig`, but with different username and email. So I only keep the common part of gitconfig in my repo, then `copy` file to different laptop.

I was thinking to refactor `link` first, but I found refactoring it is not easy. So I chose implementing `copy` first. Once we know which part of code should be shared, we could refactor it again.

**Comment by anishathalye** [comment]
I don't fully understand the gitconfig use case / how `copy` is required here (are your dotfiles open-source? I could just take a look at the code if that's easier).

I have a similar situation where my machines share a common `~/.gitconfig`, but some details differ. The way I handle it is that my main dotfiles symlink `~/.gitconfig`, and I use [this configuration](https://github.com/anishathalye/dotfiles/blob/master/gitconfig#L113-L115) to include `~/.gitconfig_local`. This file is also symlinked into place; I have a separate repo with per-machine configuration (in branches). For example, [here](https://github.com/anishathalye/dotfiles-local/blob/mac/gitconfig_local) is the `~/.gitconfig_local` I use on my laptop (`mac` branch). For all of this, I use `link`, not `copy`.

**Comment by walkingice** [comment]
thanks for the trick, I don't know that until now. :D

it seems `copy` is not necessary in any of your cases, just let me close this PR.

Thanks for your reply and this great project!

**Pull request closed without merging**
