### PR TITLE
Load configuration file in order

### PR DESCRIPTION
**Pull request by PacketPerception**
I have a use case where it is important that links are created in the order that listed, e.g.

```
- link:
    ~/.pyenv: contrib/pyenv
    ~/.pyenv/plugins/pyenv-virtualenv: contrib/pyenv-virtualenv
```
This way I don't have to modify the pyenv submodule to add pyenv-virtualenv as a submodule to it.

I've implemented this by having pyyaml load using an OrderedDict rather than a dict. I also added a test that I confirmed will fail with the default loading.

### CODE REVIEW

**Comment by anishathalye** [comment]
Hmm, there is already a way to express order in the current syntax:

```
- link:
    ~/.pyenv: contrib/pyenv
- link:
    ~/.pyenv/plugins/pyenv-virtualenv: contrib/pyenv-virtualenv
```

It does involve repeating the "link", so that's slightly annoying, but it's possible. I don't know if there's enough of a benefit by using ordereddicts that it's worth doing this.

**Comment by PacketPerception** [comment]
Yeah, I've recently come to realize this. I guess the question would be,
are there any downsides to using the ordered dicts then? It seems nice to
me to have a more intuitive set of actions take place than the somewhat
(seemingly) random order you get with the default behavior.

**Comment by anishathalye** [comment]
It doesn't cause any breakage to use the given order (because it's one specific ordering of the things in the dictionary, and any ordering is acceptable). However, I think if we add this functionality, people will start relying on it, and then we'll be forced to maintain dealing with ordered dictionaries, having an alternative interpretation of JSON/YAML.

**Comment by PacketPerception** [comment]
I'm not sure I follow on the different interpretation of JSON/YAML. Since JSON is a subset of YAML, the YAML loader does the job for both formats, so the same code works for both.

**Comment by anishathalye** [comment]
By interpretation of JSON/YAML, I'm not talking about the code working properly to interpret stuff as ordered.

In the JSON / YAML spec, dictionaries are not considered ordered. Like the JSON `{"a": 1, "b": 2}` and the JSON `{"b": 2, "a": 1}` are describing the same structure. Interpreting the two JSONs differently seems to diverge from the JSON spec/semantics.

**Comment by anishathalye** [comment]
I'm going to go ahead and close this. There is already a way of specifying the order in which to do things, so I don't think there's an advantage in using ordered dictionaries.

**Comment by anishathalye** [comment]
I appreciate you taking the time to submit the patch.

By the way, in the future, you might save time if you open an issue to start a discussion before working on patch.

**Pull request closed without merging**
