### PR TITLE
Adjust docs to fix execution permission on install

### PR DESCRIPTION
**Pull request by felipecassiors**

### CODE REVIEW

**Comment by felipecassiors** [comment]
About the `install.conf.yaml`, what do you think @anishathalye?

**Comment by anishathalye** [comment]
Rather than change the instructions, what if we change Dotbot to accept an empty configuration file (and warn on this condition). E.g.

```console
$ touch install.conf.yaml
$ ./install
Configuration file is empty, no work to do

==> All tasks executed successfully
```

**Comment by felipecassiors** [comment]
Yes, you're right. That would be better. I'll adjust the PR.

**Comment by anishathalye** [comment]
Ah I meant something more like 3b6b6f41614e1c6f346f6ac47d3bd5781d918695.

It's not necessary to `chmod +x` the `install` file, it's already set as executable in `tools/git-submodule/install`, so when it's copied, it will retain that permission.

**Comment by felipecassiors** [comment]
@anishathalye It retains the permission only in the local file system, not on git. In other words, if you clone the repository later, you won't have the execution permission on the `install`, causing then `no permission to execute` error.

**Comment by anishathalye** [comment]
The file is already chmod +x, so when it's `git add`ed by the user eventually, git will track its permissions.

I tried it out, following the instructions in the readme:

```console
$ mkdir dotfiles
$ cd dotfiles
$ git init
Initialized empty Git repository in /private/tmp/dotfiles/.git/
$ git submodule add https://github.com/anishathalye/dotbot
Cloning into '/private/tmp/dotfiles/dotbot'...
remote: Enumerating objects: 125, done.
remote: Counting objects: 100% (125/125), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 1030 (delta 65), reused 91 (delta 44), pack-reused 905
Receiving objects: 100% (1030/1030), 248.09 KiB | 913.00 KiB/s, done.
Resolving deltas: 100% (565/565), done.
$ git config -f .gitmodules submodule.dotbot.ignore dirty
$ cp dotbot/tools/git-submodule/install .
$ touch install.conf.yaml
$ git add .; git commit -m 'Initial commit'
[master (root-commit) 1178f28] Initial commit
 4 files changed, 20 insertions(+)
 create mode 100644 .gitmodules
 create mode 160000 dotbot
 create mode 100755 install
 create mode 100644 install.conf.yaml
$ cd ..
$ git clone dotfiles dotfiles2
Cloning into 'dotfiles2'...
done.
$ cd dotfiles2
$ ls -l
total 4
drwxr-xr-x 2 anish wheel  64 Jun 25 18:57 dotbot
-rwxr-xr-x 1 anish wheel 368 Jun 25 18:57 install
-rw-r--r-- 1 anish wheel   0 Jun 25 18:57 install.conf.yaml
$ ./install
Submodule 'dotbot' (https://github.com/anishathalye/dotbot) registered for path 'dotbot'
Cloning into '/private/tmp/dotfiles2/dotbot'...
Submodule path 'dotbot': checked out 'c5e709d433bdd6694ad68b67978b655a57f740df'
Submodule 'lib/pyyaml' (https://github.com/yaml/pyyaml) registered for path 'dotbot/lib/pyyaml'
Cloning into '/private/tmp/dotfiles2/dotbot/lib/pyyaml'...
Submodule path 'dotbot/lib/pyyaml': checked out '2f463cf5b0e98a52bc20e348d1e69761bf263b86'
Configuration file is empty, no work to do

==> All tasks executed successfully
```

**Comment by felipecassiors** [comment]
Yes, you're right. Just tried here. For some reason, I faced this issue when I was creating my dotfiles repo. 

My bad, really sorry about that.

**Pull request closed without merging**
