### PR TITLE
[RFC] Add default options

### PR DESCRIPTION
**Pull request by aykamko**
Adds default options as discussed in #35 

`defaults` didn't seem like a plugin-able action to me, so I wrote it as a special case.

### CODE REVIEW

**Comment by anishathalye** [comment]
I like it! Let's leave the discussion open for a little bit before merging so we can get feedback from others like @casey who were involved in the discussion about this.

Once that's done, we should add to the documentation in the readme as well, and we should probably add a test case.

**Comment by aykamko** [comment]
@anishathalye sounds good!

**Comment by casey** [comment]
Looks good!

I added a comment about doing some extra validation on the defaults object. It would be a good opportunity to print a helpful error message, and hopefully make it easier for users to debug config files, for example if they misspell a directive.

It looks like with this implementation we support multiple defaults blocks, with the semantics that each defaults block overrides the previous one. I think this is reasonable, but we should definitely call that out in the readme so that people know that order matters.

Another thing to think about is that, currently, plugins are able to implement the "can_handle(action)" method, which gives them considerable flexibility in which actions they can handle. They could, for example, handle any action that matches a regex, for example "remote-shell-[a-z0-9]+" and then run a command on a remote host with that name. I don't think anyone is taking advantage of this, but the possibility is there.

Given that, there's a little bit of a mismatch between how defaults get passed to plugins. `self._defaults.get(action, {}))` will do exact string matching, so a plugin that accepts patterns will only get the defaults value which matches the exact string that it is currently handling.

I don't think this really matters, since no plugin I know of actually accepts patterns, but it's good to keep in mind.

**Comment by aykamko** [comment]
@casey Yeah, I was actually thinking that passing `defaults` in to `handle()` seemed a little too restrictive. For example, what if some particular plugin wanted to reference defaults from another plugin? The way I set it up in this PR wouldn't allow for that.

I think a better solution might be to pass a reference to a global `plugin_defaults` dict when we `__init__` each plugin in `_load_plugins`. This would solve both the problem @casey poses and the one I just mentioned. As an added precaution, we could make `plugin_defaults` immutable for plugins. It would only be mutable through the special `defaults` directive handled by the `Dispatcher`.

@anishathalye Thoughts? This would be a slight restructure to the plugin interface.

**Comment by anishathalye** [comment]
Random thought -- I don't know if this is actually a problem, but this will break old plugins (function arity mismatch). Not sure if we consider the current plugin interface stable (can this not land in v1.x / do we need a major version bump because we're breaking backwards compatibility).

I like supporting multiple `- defaults` directive (it seems more reasonable than having a somewhat arbitrary restriction that it can be done only once). Every time we specify another defaults set, we could either update (merge dicts) or replace. I like the idea of building a solution that allows for plugins to peek at the entire defaults dictionary for the reason that @casey mentioned.

Not sure exactly how the design should look (additional arg vs reference to global plugin_defaults dict). Another way is to add some object to manage this using a new `Context` object. So like the Plugin's current ivar `base_directory` would instead be accessed through a reference to a context object that the plugin has, `self.context.base_directory()`, and we could also have a method to get defaults like `self.context.defaults()`. Just another way of doing it.

I'm not sure if this is actually a good design. I'm kinda sleep-deprived at the moment, so I'll think about it again tomorrow when I'm more awake.

**Comment by casey** [comment]
I think between merging subsequent defaults blocks and replacing them, I like replacing better, just because it's easier to keep track of, and there will probably be fewer surprises for users.

**Comment by anishathalye** [comment]
Okay, makes sense, +1 for replacing rather than updating.

**Comment by anishathalye** [comment]
Okay, I implemented a modified version of @aykamko's contribution: https://github.com/anishathalye/dotbot/commit/4f8a1cd6b7e8e1385489174695f9927954416a6e (with documentation and tests; credits in commit message).

It's currently on the develop branch, not merged into master.

How does it look?

**Comment by anishathalye** [comment]
@casey thanks for the quick feedback on the patch!

I'll merge this in a day or two if there's no other feedback from anyone.

(I realize that this is slightly breaking the plugin API but I don't think it's a big deal, I don't think anyone is actually using plugins, and if they are, it should be a one minute fix.)

**Comment by anishathalye** [comment]
Ok, made some finishing touches and merged in f52bbd1eec0d6fb103c5fcbb75c03ca223fffdb7.

If there's anything else that needs to be changed, the change can be applied on top.

**Pull request closed without merging**
