### PR TITLE
Ability to use environment variables in link paths

### PR DESCRIPTION
**Pull request by PacketPerception**
Added the ability to use environment variables in link paths, and set up the HOSTNAME environment variable if it isn't already set. This makes linking host specific configs very easy by hostname, and leaves the potential to use other environment variables in the paths.

For example:
```yaml
- link:
    ~/.gitconfig: host/$HOSTNAME/gitconfig
```

Feel free to use or not, works well for my use case.

### CODE REVIEW

**Comment by anishathalye** [comment]
Thanks for the patch. It'll probably be a couple days before I can take a look at this.

**Comment by anishathalye** [comment]
Okay, turns out that I had some time today. A couple thoughts:

* I thought that `expandvars()` might expand unset variable names to the empty string, which could result in bad things like [this](http://www.slashgear.com/steam-on-linux-bug-can-delete-all-users-files-16364945/) happening. Fortunately, according to the [documentation](https://docs.python.org/2/library/os.path.html#os.path.expandvars), it leaves unset variables unchanged.
* This could make it possible to support the XDG base directory specification (see #23), although I guess it would be kinda nice to add syntactic sugar for that at some point.
* Setting the hostname seems like it shouldn't be something that is done in Dotbot itself. If someone wants to do that, they could add a line to the `install` script like `export HOSTNAME="$(hostname)"`.
* If we support variable expansion when linking, I think we need variable expansion in the `_delete()` method, linker.py:79 too.

One thing to consider:

* If we support variable expansion in the source, should we support variable expansion in the target as well? So then something like this would be okay: `~/$HOSTNAME: path/file`

**Comment by PacketPerception** [comment]
Agreed with exporting $HOSTNAME in the install script, no idea why that didn't occur to me. I see no reason not to support expandvars in the source as well. Supporting in the delete method would be good as well.

**Comment by anishathalye** [comment]
All right, I got around to implementing this: https://github.com/anishathalye/dotbot-dev/commit/5fcfde53ae31885025943ab2c9af0a17d3806bab

This required pretty minimal changes in the code (2 lines). I also added a couple tests for the feature.

I've credited you in the commit message. Let me know if it looks okay :)

**Comment by PacketPerception** [comment]
Looks good to me! Thanks for the great project, it's been making my life a whole lot simpler.

**Comment by anishathalye** [comment]
Okay, I'm going to push this (fd7f3b85 / tag v1.6.0).

Thanks for the idea for the patch!

**Pull request closed without merging**
